= Emercoin
include::config.adoc[]
include::links.adoc[]

Emercoin (EMC) - это криптовалюта с гибридной PoS и PoW добычей (при этом объединенная с биткойнами). Генерация монет ориентирована в основном на производство монет с помощью энергосберегающих PoS, поскольку сложность PoW постепенно увеличивается с течением времени.

Общий объем предложения::
Алгоритмическое увеличение прибл. 6% в год, {emer-stats}[статистика].

Частота создания блока::
В среднем за 10 минут

Алгоритм PoW::
SHA-256 (объединенный с биткойнами).

Вознаграждение за блок PoW::
5020 EMC, уменьшается в зависимости от сложности PoW.
Формула:::
Награда = 5020 / sqrt (sqrt (сложность)) 

Награда PoS::
Приблизительно 6% годовых.

Срок созревания монет для PoS::
30 дней.

Максимальный возраст монет для PoS::
90 дней.

Регулировка сложности::
Пересчет идет каждый блок. Зависит от сложности PoW

Срок зрелости вновь добытой награды::
32 блока, пока не будут потрачены новые монеты.

Base58Check кодировка префикс адреса (en)::
33

Порт p2p по умолчанию::
6661

Порт RPC по умолчанию::
6662

---





[#installation]
[desc="Установка, сборка из исходных кодов"]
== Installation
include::chapters/installation.adoc[]

[#nvs_subsystems]
[desc="Описание Name Value Storage и подсистем созданных на его основе"]
== NVS и его подсистемы
include::chapters/nvs_subsystems.adoc[]

[#randpay]
[desc="Подсистема массовых микроплатежей"]
== RandPay
include::chapters/randpay.adoc[]

[desc="Майнинг Pos, PoW"]
[#mining]
== Mining
include::chapters/mining.adoc[]

[#articles]
[desc="Статьи и видеоматериалы связанные с Emercoin"]
== Статьи
include::chapters/articles.adoc[]

[#other]
[desc="Все что не вошло в основные главы, песочница"]
== Other
include::chapters/other.adoc[]




