EmerMAGNET - это хранилище магнитных ссылок BitTorrent под аббревиатурой сервиса **«magnet»** в EmerNVS.

Разместив ссылку в Emer, вы никогда не потеряете свой любимый торрент.

Как это работает? Блокчейн хранит вечно любую информацию, верно? Вот мы и подумали, сколько бывало -- ищещь какой-нибудь старый фильм, а его и след простыл, остались только левые копии с совсем не тем перводом и т.п. Так вот, магнет-ссылка в блокчейне никуда не денется и придет время, её обязательно найдут. (правда останутся ли копии того фильма на дисках энтузиастов, но это другой вопрос)

EmcMAGNET - это хранилище {magnet-lnk-explain}[магнитных ссылок BitTorrent] под аббревиатурой сервиса «magnet» в Emercoin NVS.

Магнитные ссылки должны использовать следующий формат имя-> значение :
----
"name" : "magnet:Emercoin 0.3.2 for Linux - packed as tar.gz, original file from emercoin.com"
"value" : "magnet:?xt=urn:btih:dff183bcac72a628fcac88ac1c85c239b806fd5e&dn=emercoin-0.3.2-linux.tar.gz"
----

Список всех магнитных ссылок можно получить с помощью следующей команды с Emercoin API :
----
$ emercoin-cli name_filter '^magnet:'
----
