include::../links.adoc[]

Бинарные версии для вашей платформы можно скачать {emercoin-github}[здесь].


Arch Linux:
----
yay -S emercoin-bin
----

=== Docker

Существуют готовые образы Docker, запустив которые вы сразу получите готовую сборку Emercoin.

* Официальный {emer-docker-oficial}[репозиторий]
* Неофициальный {emer-docker-unoficial}[репозиторий]
+
NOTE: Образы в неофициальном репозитории скомплированы с версией BerkleyDB 5.3 поэтому wallet.dat от других версий не подхватиться

=== Сборка из исходных кодов

[quote, Кто то из разработчиков]
____
The Emercoin team happy to inform: we have written and released version 0.7.11, see the binaries and release notes on Github: https://github.com/emercoin/emercoin/releases/tag/v0.7.11emc

However, you can get the binaries for PC and Linux from the Github link above. Please, upgrade the Emercoin node on your system, it contains several important (but not critical) bugfixes.

Please inform us when you will upgrade your system.

If you prefer to build the program yourself, do it by following way:
____

----
git clone git@github.com:emercoin/emercoin.git
cd emercoin/
git checkout tags/v0.7.11emc
./autogen.sh
./configure --disable-dependency-tracking --disable-tests --disable-util-tx --disable-gui-tests --enable-bip70 --disable-hardening --disable-debug
make -j 4
----

=== Emercoin.conf

.Send commands to node running on <ip> (default: 127.0.0.1)
----
-rpcconnect=<ip>
----

.Connect to JSON-RPC on <port> (default: 6662 or testnet: 6662)
----
-rpcport=<port>
----

.Username for JSON-RPC connections
----
-rpcuser=<user>
----

.Password for JSON-RPC connections
----
-rpcpassword=<pw>
----

.Timeout during HTTP requests (default: 900)
----
-rpcclienttimeout=<n>
----

.Specify configuration file (default: emercoin.conf)
----
-conf=<file>
----

.Specify data directory
----
-datadir=<dir>
----

.Алгоритм сортировки используемых UTXO при генерации транзакции. 0 - cлучайное перемешивание, 1 - сортировка по времени вылёживания (свежие раньше).
----
-sortir
----

.Разбиение выхода транзакции при PoS. 0 -- не разбивать. 1 -- разбиение примерно пополам (default).-1 -- Разбиение на основное тело и награду. Если транзакция на 1000 emc, прошла через POS, заработала 60EMC. Разбиение будет на 1000 и 60.
----
-splitpos
----

.Set the proxy server. If SOCKS5 is selected (default), this proxy server will be used to try to reach .onion addresses as well. You need to use -noonion or -onion=0 to explicitly disable     outbound access to onion services.
----
-proxy=ip:port
----

.Set the proxy server to use for Tor onion services. You do not need to set this if it's the same as -proxy. You can use -onion=0 to explicitly disable access to onion services.
----
-onion=ip:port
----

.When using -proxy, listening is disabled by default. If you want to manually configure an onion service (see section 3), you'll need to enable it explicitly.
----
-listen
----




GetBoolArg

.Use the test chain
----
-testnet
----

.Pass named instead of positional arguments (default: false)
----
-named
----

.Wait for RPC server to start
----
-rpcwait
----

.Read extra arguments from standard input, one per line until EOF/Ctrl-D (recommended for sensitive information such as passphrases)
----
-stdin
----

.Enter regression test mode, which uses a special chain in which blocks can be solved instantly. This is intended for regression testing tools and app development
----
-regtest
----



----
-acceptnonstdtxn
-alerts
-allowselfsignedrootcertificates
-benchmark
-blocksonly
-checkblockindex
-checkpoints
-create
-daemon
-datacarrier
-debugnet
-disablewallet
-discover
-dns
-dnsseed
-emcdns
-exchtest
-feefilter
-flushwallet
-forcednsseed
-gen
-help-debug
-json
-legacyrpc
-listenonion
-logips
-logtimemicros
-logtimestamps
-mempoolreplacement
-min
-nameaddress
-nodebug
-peerbloomfilters
-permitbaremultisig
-prematurewitness
-printcoinage
-printcoinstake
-printcreation
-printfee
-printpriority
-printselectcoin
-printstakemodifier
-printtoconsole
-privdb
-proxyrandomize
-reindex
-reindex-chainstate
-relaypriority
-rescan
-rest
-rpcssl
-salvagewallet
-server
-shrinkdebugfile
-spendzeroconfchange
-splash
-stakegen
-stopafterblockimport
-sysperms
-testsafemode
-tor
-txid
-txindex
-upgradewallet
-upnp
-usehd
-walletbroadcast
-walletprematurewitness
-walletrbf
-walletrejectlongchains
-whitelistalwaysrelay
-whitelistforcerelay
-whitelistrelay
-zapwallettxes
----

.GetArg
----
-adjustexch
-assumevalid
-banscore
-bantime
-blockmaxsize
-blockmaxweight
-blockmintxfee
-blockprioritysize
-blockreconstructionextratxn
-blockversion
-bytespersigop
-changeaddress
-checkblocks
-checklevel
-checkpointdepth
-checkpointnode
-checkpointpubkey
-checkpointslots
-dapsize
-daptreshold
-datacarriersize
-dbcache
-dblogsize
-dustrelayfee
-emcdnsallowed
-emcdnsbindip
-emcdnslocalcf
-emcdnsport
-emcdnssuffix
-emcdnsverbose
-enumtollfree
-enumtrust
-genproclimit
-incrementalrelayfee
-keypool
-limitancestorcount
-limitancestorsize
-limitdescendantcount
-limitdescendantsize
-limitfreerelay
-maxconnections
-maxdp
-maxmempool
-maxreceivebuffer
-maxsendbuffer
-maxtipage
-maxtxfee
-maxuploadtarget
-mempoolexpiry
-minrelaytxfee
-mocktime
-modcache
-nameindexchainsize
-onion
-par
-paytxfee
-port
-posprotect
-promiscuousmempoolflags
-prune
-randkeymapsz
-reservebalance
-rpcserialversion
-rpcservertimeout
-staketimio
-stunsrcport
-timeout
-torcontrol
-txconfirmtarget
-uiplatform
----