

Emercoin предоставляет сервис для хранения пар имя -> значение в своей цепочке блоков Name-Value Storage или NVS. Первоначальная концепция была унаследована от криптовалюты {namecoin}[NameCoin], но в то время как NameCoin в основном ориентирована на поддержку децентрализованной доменной зоны .bit в своем расширении, Emercoin предоставляет универсальный расширяемый сервис для хранения и поддержки пар имя -> значение без навязывания узкой специализации.

Конечно, Emercoin также поддерживает {alt-dns-root}[распределенную альтернативную службу DNS], и каждый кошелек Emercoin содержит встроенный простой DNS-сервер, поддерживающий стандартный протокол DNS {rfc1034}[RFC1034] UDP.

[discrete]
=== Обзор NVS
Emercoin хранит данные в блокчейне по набору пар имя -> значение:

* name - метка для сохраненных данных длиной до 512 байт.
* value - сами данные, длиной до 20 * 1024 (20кб).

Emercoin выделяет до 20 КБ для каждого имени, что достаточно для размещения открытых ключей для большинства современных криптографических приложений. Мы считаем, что блокчейн криптовалюты является чрезвычайно надежным местом для публикации и поддержки открытых ключей для многих криптографических приложений, таких как сертификаты SSH/SSL. Как и обычные платежные транзакции, пары NVS, хранящиеся в блокчейне, также получают подтверждения во время генерации блока и практически неуязвимы для изменения в результате {атака-посредника}[Атаки Посредника].

Поскольку блокчейн является надежным хранилищем данных, защищенным от несанкционированного изменения, он является отличной основой для развертывания криптографической {pki}[Public Key Infrastructure] (PKI), цифрового подтверждения владения (DPO), неизменяемого ведения записей, временных меток и других распределенных сервисов.

Блокчейн Emercoin будет принимать пары NVS без каких-либо ограничений на формат данных имени или значения. Однако в целях стандартизации мы рекомендуем следующий формат имен:

 <service_abbreviation>:<unique_key>


Например:

 dns:emercoin.com


У каждой пары NVS есть свой владелец. Каждого владельца указывает платежный адрес Emercoin, который хранится вместе с парой. Только владелец платежного адреса может изменить или удалить пару, или передать право собственности на другой адрес. Когда создается новая пара, в локальном кошельке создается новый платежный адрес для пары.

Вы можете управлять записями NVS либо через графический интерфейс кошелька Emercoin, либо через emercoin-cli.

[discrete]
=== Аббревиатуры сервисов

[cols="1,1,1"]
|===
|**Аббревиатура**|**Сервис**|**Сервис в Emercoin**

|DNS
|DNS записи
|EmerDNS

|SSH
|SSH публичные ключи
|EmerSSH

|GPG
|GNU PGP публичные ключи
|

|KX
|{rfc2230}[RFC2230] публичные ключи
|

|SSL
|SSL Сертификат
|EmerSSL

|BLS
|BLS цифровая подпись публичного ключа
|

|TTS
|Trusted Timestamp
|EmerTTS

|DPO
|Digital Proof-of-Ownership
|EmerDPO

|Magnet
|BitTorrent магнет линки
|EmerMagnet

|SWIFT
|Банковская подсистема перeводов SWIFT
|

|ENUM
|ENUM телефонные записи
|ENUMER
|===


=== EmerDNS
include::nvs_subsystems/emerdns.adoc[]

=== EmerSSL
include::nvs_subsystems/emerssl.adoc[]

=== EmerSSH
include::nvs_subsystems/emerssh.adoc[]

=== EmerDPO
include::nvs_subsystems/emerdpo.adoc[]

=== ENUMER
include::nvs_subsystems/enumer.adoc[]

=== EmerLNX (Dead)
pass

=== EmerTTS (Possible Dead)
pass

=== EmerMagnet
include::nvs_subsystems/emermagnet.adoc[]

=== FileValidator
include::nvs_subsystems/filevalidator.adoc[]
